# Generated by Django 3.1.7 on 2021-02-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='unknown code', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
