# Generated by Django 3.1.7 on 2021-04-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='static_url',
            field=models.CharField(default='../static/img/', max_length=30),
        ),
    ]
