# Generated by Django 3.1.7 on 2021-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='id',
        ),
        migrations.AlterField(
            model_name='history',
            name='page_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
