# Generated by Django 3.1.7 on 2021-03-05 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210303_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
