# Generated by Django 3.1.7 on 2021-02-25 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_product', to='main.product')),
                ('target_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_product', to='main.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.user')),
            ],
        ),
    ]
