# Generated by Django 3.1.7 on 2021-02-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substitution',
            old_name='source_product_id',
            new_name='source_product',
        ),
        migrations.RenameField(
            model_name='substitution',
            old_name='target_product_id',
            new_name='target_product',
        ),
        migrations.RenameField(
            model_name='substitution',
            old_name='user_id',
            new_name='user',
        ),
    ]
