# Generated by Django 3.1.7 on 2021-03-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='substitution',
            constraint=models.UniqueConstraint(fields=('target_product', 'source_product', 'user_id'), name='unique_substitution_user'),
        ),
        migrations.AlterModelTable(
            name='substitution',
            table='bookmark_substitution',
        ),
    ]
